add_newline = true

[aws]
disabled = true

[line_break]
disabled = false

[character]     
success_symbol = "[â¯](bold green) "
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 500

[openstack]
format = "on [$symbol $cloud(\\($project\\))]($style) "
style = "bold yellow"
symbol = "â˜ï¸ "

[docker_context]
symbol = "ğŸ³ "

[git_branch]
symbol = "îœ¥ "

[hg_branch]
symbol = "on [îœ¥ $branch](bold purple)"

[memory_usage]
symbol = "ğŸ "

[terraform]
format = "[ğŸ’¨ $workspace]($style) "

[nix_shell]
symbol = "â„ï¸ "

[package]
symbol = "ğŸ“¦ "

[php]
symbol = "ğŸ˜ "

[python]
symbol = "ğŸ "
style = "bold green"

[nodejs]
symbol = "ğŸ¤– "
style = "bold green"

[java]
style = "bold green"

[scala]
symbol = "ğŸ†‚ "
style = "red dimmed"

